### ISSUE TITLE
fs.exists will be deprecated

### ISSUE THREAD

**Issue by stevemao** [hemanth/node-prepend-file#3]
This is a reminder to myself.
https://github.com/sindresorhus/path-exists but we might not need it.

**Comment by sindresorhus** [comment]
For your use-case, you shouldn't use either, as outlined in the `path-exists` readme and exactly why `fs.exists` is being deprecated.

**Comment by stevemao** [comment]
Yup :smile:

**Comment by stevemao** [comment]
Fixed in 6a126fade9d944e15de2047f1f9f45afe024326a
